# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

first_number = 0
second_number = 1
fibonacci = 0
even_sum = 0

while fibonacci <= 4000000:
    fibonacci = first_number + second_number
    first_number = second_number
    second_number = fibonacci

    if fibonacci % 2 == 0:
        even_sum = even_sum + fibonacci

print("Sum of even fibonacci number of which are less than 4 million is:", even_sum)

